export const ENDPOINTS = {
  CATEGORIES: 'categories',
  COURSES: 'courses',
  FACILITATORS: 'facilitators',
  REGISTER: 'register',
  LOGIN: 'login',
  LOGOUT: 'logout',
  USERS: 'admin/users',
  PENDING_USERS: 'admin/pending-users',
  ACCEPTED_USERS: 'admin/accepted-users',
  ADD_USER: 'admin/create-user',
  DELETE_USER: 'admin/delete-user-account',
  VALIDATE_USER: 'admin/validate-user-account',
  REJECT_USER: 'admin/reject-user-account',
  SUSPEND_USER: 'admin/suspend-account',
  EDIT_USER: 'admin/update-user-account',
  SET_PASSWORD: 'password-set/?token=',
  SEND_RESET_PASSWORD_EMAIL: 'send-password-reset-mail',
  DESIGNER_COURSES: 'designer/courses',
  DELETE_COURSE: 'designer/delete-course',
  LANGUAGES: 'languages',
  ACTIVE_USERS: 'designer/users',
  CREATE_COURSE: 'designer/create-course',
  CREATE_MODULE: 'designer/create-step',
}
