export const GLOBAL_VARIABLES = {
  TRUE_STRING: 'true',
  FALSE_STRING: 'false',
  EMPTY_STRING: '',

  APP_LAYOUT: { DRAWER_WIDTH: 240 },
  PAGINATION: {
    FIRST_PAGE: 1,
    CHUNK_ROWS_PER_PAGE: 6,
    ROWS_PER_PAGE: 15,
  },
  DEBOUNCE_TIME: {
    SHORT: 500,
    MEDIUM: 700,
    LONG: 1000,
  },
}
